### ISSUE TITLE
['Add a Lesson' page] Error page appears on Lesson save

### ISSUE THREAD

**Issue by CaelumVallis** [ita-social-projects/what-front#622] opened 2021-06-04 12:40 UTC
Preconditions

WHAT project launched locally using npm.
The project is opened in the browser. URL: 'http://localhost:8080/lessons/add'.
Steps to reproduce

Fill the lesson form with valid data.
Click 'Class Register' button.
Fill students' marks (optional)
Error page appears.

Expected result
Everything is alright, lesson is created.

![image](https://user-images.githubusercontent.com/64030284/120803084-db748e00-c54b-11eb-9363-0eed28ca227e.png)

**Comment by AllaYakymova** [comment] 2021-06-09 12:14
The cause of this bug was fixed in the issue #583 ['Edit a Lesson' page] 'Lesson Date/Time' field isn't displayed date and time of chosen lesson (pr #632 ).
The bug is not reproduced.

https://user-images.githubusercontent.com/62800248/121352237-51ef0280-c935-11eb-8b5c-192e2857b08c.mp4

**Closed** 2021-06-09 12:15 UTC
Labels: 1 point, bug
